# Generated by Django 2.2 on 2022-04-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0002_mob_t_tranche_stp_internal_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mob_t_tranche',
            name='STP_INTERNAL_RATING',
        ),
        migrations.AddField(
            model_name='mob_t_operation',
            name='STP_INTERNAL_RATING',
            field=models.FloatField(null=True),
        ),
    ]
