# Generated by Django 2.2 on 2022-04-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0003_auto_20220407_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mob_t_operation',
            name='STP_INTERNAL_RATING',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mob_t_rating',
            name='INTERNAL_RATING',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mob_t_rating',
            name='PD_RATING',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
